[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/tarefas/*"
  to = "http://localhost:3000/tarefas/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
