[build]
  publish = "public"
  command = "npm run build"

[functions]
  directory = "functions"  # Diretório onde suas funções estão localizadas

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
