[build]
  publish = "public"  # Diretório onde seus arquivos estáticos estão localizados
  command = "npm run build"  # Se você tiver um comando de build definido no package.json

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
